In [2]:
import pandas as pd

In [3]:
entropy = pd.read_csv('tabela_entropy.csv')
gini = pd.read_csv('tabela_gini.csv')

In [13]:
entropy.sort_values(by=['F-Score'], ascending=False)

   Critério  profundidade  Qtd. Caracteristicas  Qtd. Nós folhas  F-Score
7   Entropy           500                     4                8   0.5217
9   Entropy            10                     5                5   0.5185
11  Entropy            50                     5                7   0.5180
13  Entropy            25                     7               11   0.5176
16  Entropy            35                     6               10   0.5134
4   Entropy           350                     7                8   0.5130
12  Entropy           100                     6                9   0.5120
3   Entropy           250                     6                7   0.5063
14  Entropy           150                     5               13   0.5053
15  Entropy            75                     7               15   0.5046
1   Entropy           300                     4                6   0.5034
5   Entropy           450                     5                9   0.4982
2   Entropy           400                     5                6   0.4908
8   Entropy            10                     3                5   0.4869
6   Entropy           550                     5               12   0.4786
0   Entropy           200                     3                5   0.4709
10  Entropy             5                     4                6   0.4702

In [14]:
gini.sort_values(by=['F-Score'], ascending=False)

   Critério  profundidade  qtd. Características  Qtd. Nós folha  F-Score
11     Gini           400                     5               6   0.5211
15     Gini           550                     5              12   0.5123
13     Gini           350                     7               8   0.5103
4      Gini           100                     6               9   0.5057
3      Gini            50                     5               7   0.5051
12     Gini           250                     6               7   0.5048
7      Gini            75                     7              15   0.5048
1      Gini            10                     5               5   0.5048
2      Gini             5                     4               6   0.4993
14     Gini           450                     5               9   0.4990
8      Gini            35                     6              10   0.4973
6      Gini           150                     5              13   0.4959
0      Gini            10                     3               5   0.4913
10     Gini           300                     4               6   0.4882
16     Gini           500                     4               8   0.4820
9      Gini           200                     3               5   0.4702
5      Gini            25                     7              11   0.4702